title: toastkidjp official
description: This page is toastkidjp's official site. toastkidjp is a Japanese programmer who likes GUI apps.
show_downloads: true
google_analytics: G-KK206BWSDN
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
