title: toastkidjp official
description: This page is toastkidjp's official site. toastkidjp is a Japanese programmer, GUI app developer.
show_downloads: true
google_analytics: G-KK206BWSDN
markdown: GFM
url: "https://toastkidjp.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
